-- Table: property.property_grz_ldcap_rules

-- DROP TABLE IF EXISTS property.property_grz_ldcap_rules;

CREATE TABLE IF NOT EXISTS property.property_grz_ldcap_rules
(
    fid integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    rule_name text COLLATE pg_catalog."default" NOT NULL,
    rule_group text COLLATE pg_catalog."default" NOT NULL,
    value_numeric numeric,
    value_text text COLLATE pg_catalog."default",
    value_bool boolean,
    description text COLLATE pg_catalog."default",
    updated_at timestamp without time zone DEFAULT now(),
    geom geometry(MultiPolygon,2193) DEFAULT st_geomfromtext('MULTIPOLYGON EMPTY'::text, 2193),
    CONSTRAINT property_grz_ldcap_rules_pkey PRIMARY KEY (rule_name)
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS property.property_grz_ldcap_rules
    OWNER to postgres;

REVOKE ALL ON TABLE property.property_grz_ldcap_rules FROM wdc_gisprod;

GRANT ALL ON TABLE property.property_grz_ldcap_rules TO postgres;

GRANT ALL ON TABLE property.property_grz_ldcap_rules TO wdc;

GRANT SELECT ON TABLE property.property_grz_ldcap_rules TO wdc_gisprod;
-- Index: ux_property_grz_ldcap_rules_rule_name

-- DROP INDEX IF EXISTS property.ux_property_grz_ldcap_rules_rule_name;

CREATE UNIQUE INDEX IF NOT EXISTS ux_property_grz_ldcap_rules_rule_name
    ON property.property_grz_ldcap_rules USING btree
    (rule_name COLLATE pg_catalog."default" ASC NULLS LAST)
    TABLESPACE pg_default;