-- PROCEDURE: property.create_mv_property_grz_ldcap_overlays()

-- DROP PROCEDURE IF EXISTS property.create_mv_property_grz_ldcap_overlays();

CREATE OR REPLACE PROCEDURE property.create_mv_property_grz_ldcap_overlays(
	)
LANGUAGE 'sql'
AS $BODY$
DROP MATERIALIZED VIEW IF EXISTS property.property_grz_ldcap_overlays;

CREATE MATERIALIZED VIEW property.property_grz_ldcap_overlays
TABLESPACE pg_default
AS

WITH prop AS
(
    SELECT prop_no, ST_Buffer(geom, -1) as buffer, geom from property.property
)
SELECT row_number()OVER(ORDER BY r.prop_no)::integer AS fid, r.*
FROM
(

    SELECT 
		DISTINCT p.prop_no,
	    a.layer,
		a.min_lot_size_overlay,
		p.geom
    FROM
    (
        SELECT 
		'north_west_structure_plan_overlay' as "layer"
		,800 as min_lot_size_overlay
		,geom
        FROM eplan.north_west_structure_plan_overlay

		/*
		UNION ALL

		SELECT 
		'property_grz_ldcap_overlay_min650m2' as "layer"
		,650 as min_lot_size_overlay
		,geom
        FROM property.property_grz_ldcap_overlay_min650m2
		*/


    )as a,
    (select * from prop)as p
    WHERE ST_Intersects(p.buffer, a.geom)
)as r

WITH DATA;

ALTER TABLE property.property_grz_ldcap_overlays
    OWNER TO postgres;

GRANT ALL ON TABLE property.property_grz_ldcap_overlays TO postgres;
GRANT ALL ON TABLE property.property_grz_ldcap_overlays TO wdc;
GRANT SELECT ON TABLE property.property_grz_ldcap_overlays TO wdc_gisprod;

CREATE INDEX planning_property_grz_ldcap_overlays_fid_idx
    ON property.property_grz_ldcap_overlays USING btree
    (fid)
    TABLESPACE pg_default;
CREATE INDEX planning_property_grz_ldcap_overlays_prop_no_idx
    ON property.property_grz_ldcap_overlays USING btree
    (prop_no)
    TABLESPACE pg_default;
CREATE INDEX planning_property_grz_ldcap_overlays_geom_idx
    ON property.property_grz_ldcap_overlays USING gist
    (geom)
    TABLESPACE pg_default;

DO
$do$
BEGIN
EXECUTE format($$COMMENT ON MATERIALIZED VIEW property.property_grz_ldcap_overlays is 'Regenerated by Stored Procedure %s'$$, LOCALTIMESTAMP);
END
$do$
$BODY$;

ALTER PROCEDURE property.create_mv_property_grz_ldcap_overlays()
    OWNER TO postgres;

GRANT EXECUTE ON PROCEDURE property.create_mv_property_grz_ldcap_overlays() TO PUBLIC;

GRANT EXECUTE ON PROCEDURE property.create_mv_property_grz_ldcap_overlays() TO postgres;

GRANT EXECUTE ON PROCEDURE property.create_mv_property_grz_ldcap_overlays() TO wdc;

GRANT EXECUTE ON PROCEDURE property.create_mv_property_grz_ldcap_overlays() TO wdc_gisprod;

