-- PROCEDURE: property.create_mv_property_grz_ldcap_fully_developed_testing()

-- DROP PROCEDURE IF EXISTS property.create_mv_property_grz_ldcap_fully_developed_testing();

CREATE OR REPLACE PROCEDURE property.create_mv_property_grz_ldcap_fully_developed_testing(
	)
LANGUAGE 'sql'
AS $BODY$
DROP MATERIALIZED VIEW IF EXISTS property.property_grz_ldcap_fully_developed_testing;

CREATE MATERIALIZED VIEW property.property_grz_ldcap_fully_developed_testing
TABLESPACE pg_default
AS

-- ---------------------------------
-- Excluded properties
-- ---------------------------------
WITH excl AS (

SELECT DISTINCT prop_no
FROM (

    -- 1a. Facilities: Health facilities, Rest Homes, Pensioner Housing, Schools, Campgrounds, Prisons, Justice Facilities, Marae, Religious Activities, Fuel Facilities 
    SELECT p.prop_no
    FROM property.property p
    CROSS JOIN (
        SELECT ST_Union(geom) AS geom 
        FROM general.whanganui_local_facilities
    ) wlf
    WHERE ST_Intersects(ST_PointOnSurface(p.geom), wlf.geom)

    UNION ALL

    -- 1b. Open Space Zone
    SELECT p.prop_no
    FROM property.property p
    CROSS JOIN (
        SELECT ST_Union(geom) AS geom 
        FROM eplan.osz_open_space_zone
    ) osz
    WHERE ST_Intersects(ST_PointOnSurface(p.geom), osz.geom)

    UNION ALL

    -- 2. Non-dominant GRZ
    SELECT prop_no
    FROM property.property_eplan_zones_multiples
    WHERE layer = 'grz_general_residential_zone'
      AND overlap < 40

	UNION ALL

	-- infill property
	SELECT prop_no
	FROM property.property_grz_ldcap_infill_viability_testing

	UNION ALL

	-- vacant property
	SELECT prop_no
	FROM property.property_grz_ldcap_vacant_viability_testing

) ex
)

-- ---------------------------------
-- GRZ filtered properties
-- ---------------------------------
,pgrz AS (
SELECT p.prop_no, p.geom
FROM property.property_eplan_zones p
WHERE p.layer = 'grz_general_residential_zone'
AND NOT EXISTS (
    SELECT 1 FROM excl e WHERE e.prop_no = p.prop_no
)
)

-- ---------------------------------
-- Final output with property geometry and maximum inscribed circle geometry (building platform test)
-- ---------------------------------
SELECT 
    row_number() OVER (ORDER BY p.prop_no) AS fid,
    p.prop_no,
	'Developed' AS potential_land_development_type,
    mic.radius,
    ST_Area(ST_Buffer(mic.center, mic.radius, 50)) AS platform_area,
    ST_Buffer(mic.center, mic.radius, 50) AS platform_geom,
    p.geom

FROM pgrz p
CROSS JOIN LATERAL ST_MaximumInscribedCircle(p.geom) AS mic

WITH DATA;

ALTER TABLE property.property_grz_ldcap_fully_developed_testing
    OWNER TO postgres;

GRANT ALL ON TABLE property.property_grz_ldcap_fully_developed_testing TO postgres;
GRANT ALL ON TABLE property.property_grz_ldcap_fully_developed_testing TO wdc;
GRANT SELECT ON TABLE property.property_grz_ldcap_fully_developed_testing TO wdc_gisprod;

CREATE INDEX property_grz_ldcap_fully_developed_testing_fid_idx
    ON property.property_grz_ldcap_fully_developed_testing USING btree
    (fid)
    TABLESPACE pg_default;
CREATE INDEX property_grz_ldcap_fully_developed_testing_prop_no_idx
    ON property.property_grz_ldcap_fully_developed_testing USING btree
    (prop_no)
    TABLESPACE pg_default;
CREATE INDEX property_grz_ldcap_fully_developed_testing_geom_idx
    ON property.property_grz_ldcap_fully_developed_testing USING gist
    (geom)
    TABLESPACE pg_default;
CREATE INDEX property_grz_ldcap_fully_developed_testing_platform_geom_idx
    ON property.property_grz_ldcap_fully_developed_testing USING gist
    (platform_geom)
    TABLESPACE pg_default;
DO
$do$
BEGIN
EXECUTE format($$COMMENT ON MATERIALIZED VIEW property.property_grz_ldcap_fully_developed_testing is 'Regenerated by Stored Procedure %s'$$, LOCALTIMESTAMP);
END
$do$
$BODY$;

ALTER PROCEDURE property.create_mv_property_grz_ldcap_fully_developed_testing()
    OWNER TO postgres;

GRANT EXECUTE ON PROCEDURE property.create_mv_property_grz_ldcap_fully_developed_testing() TO PUBLIC;

GRANT EXECUTE ON PROCEDURE property.create_mv_property_grz_ldcap_fully_developed_testing() TO postgres;

GRANT EXECUTE ON PROCEDURE property.create_mv_property_grz_ldcap_fully_developed_testing() TO wdc;

GRANT EXECUTE ON PROCEDURE property.create_mv_property_grz_ldcap_fully_developed_testing() TO wdc_gisprod;

