-- PROCEDURE: property.create_mv_property_grz_ldcap_summary_suburbs()

-- DROP PROCEDURE IF EXISTS property.create_mv_property_grz_ldcap_summary_suburbs();

CREATE OR REPLACE PROCEDURE property.create_mv_property_grz_ldcap_summary_suburbs(
	)
LANGUAGE 'sql'
AS $BODY$


DROP MATERIALIZED VIEW IF EXISTS property.property_grz_ldcap_summary_suburbs;

CREATE MATERIALIZED VIEW property.property_grz_ldcap_summary_suburbs
TABLESPACE pg_default
AS

WITH developable AS (
    SELECT 
        prop_no,
        potential_land_development_type,
        phu_yield,
        phu_yield AS developable_lots,
        land_area_ha,
        total_road_frontage,
        geom,
        CASE
            WHEN phu_yield = 1 THEN 'Single Vacant Lot'
            WHEN phu_yield BETWEEN 2 AND 6 THEN 'Small Scale Development'
            WHEN phu_yield >= 7 THEN 'Large Scale Development'
        END AS development_category
    FROM property.property_grz_ldcap_vacant_viable
    
    UNION ALL
    
    SELECT 
        prop_no,
        potential_land_development_type,
        phu_yield,
        phu_yield AS developable_lots,
        land_area_ha,
        total_road_frontage,
        geom,
        CASE
            WHEN phu_yield = 1 THEN 'Single Lot Infill'
            WHEN phu_yield BETWEEN 2 AND 6 THEN 'Small Scale Infill'
            WHEN phu_yield >= 7 THEN 'Large Scale Infill'
        END AS development_category 
    FROM property.property_grz_ldcap_infill_viable
),

developable_with_suburb AS (
    SELECT
        d.*,
        s.sa22023_v1_00_name_ascii AS suburb_name
    FROM developable d
    LEFT JOIN stats.wdc_2023_census_housing_data_by_sa2_clipped s
        ON ST_Within(
            ST_PointOnSurface(d.geom),
            s.geom
        )
),

summary AS (
    SELECT
        suburb_name,
        potential_land_development_type,
        development_category,
        COUNT(*) AS developable_properties,
        SUM(developable_lots) AS total_developable_lots,
        SUM(phu_yield) AS total_phu_yield,
        SUM(land_area_ha) AS total_land_area_ha
    FROM developable_with_suburb
    GROUP BY 
        suburb_name,
        potential_land_development_type,
        development_category
)

SELECT 
    row_number() OVER ()::integer AS fid,
    *,
    ST_GeomFromText('MULTIPOLYGON EMPTY', 2193)::geometry(MultiPolygon, 2193) AS geom
FROM summary
ORDER BY 
    suburb_name,
    potential_land_development_type,
    development_category



	

WITH DATA;

ALTER TABLE property.property_grz_ldcap_summary_suburbs
    OWNER TO postgres;

GRANT ALL ON TABLE property.property_grz_ldcap_summary_suburbs TO postgres;
GRANT ALL ON TABLE property.property_grz_ldcap_summary_suburbs TO wdc;
GRANT SELECT ON TABLE property.property_grz_ldcap_summary_suburbs TO wdc_gisprod;


DO
$do$
BEGIN
EXECUTE format($$COMMENT ON MATERIALIZED VIEW property.property_grz_ldcap_summary_suburbs is 'Regenerated by Stored Procedure %s'$$, LOCALTIMESTAMP);
END
$do$
$BODY$;

ALTER PROCEDURE property.create_mv_property_grz_ldcap_summary_suburbs()
    OWNER TO postgres;

GRANT EXECUTE ON PROCEDURE property.create_mv_property_grz_ldcap_summary_suburbs() TO PUBLIC;

GRANT EXECUTE ON PROCEDURE property.create_mv_property_grz_ldcap_summary_suburbs() TO postgres;

GRANT EXECUTE ON PROCEDURE property.create_mv_property_grz_ldcap_summary_suburbs() TO wdc;

GRANT EXECUTE ON PROCEDURE property.create_mv_property_grz_ldcap_summary_suburbs() TO wdc_gisprod;

