-- PROCEDURE: property.create_mv_property_grz_ldcap_summary()

-- DROP PROCEDURE IF EXISTS property.create_mv_property_grz_ldcap_summary();

CREATE OR REPLACE PROCEDURE property.create_mv_property_grz_ldcap_summary(
	)
LANGUAGE 'sql'
AS $BODY$


DROP MATERIALIZED VIEW IF EXISTS property.property_grz_ldcap_summary;

CREATE MATERIALIZED VIEW property.property_grz_ldcap_summary
TABLESPACE pg_default
AS

WITH developable AS (
    SELECT 
        prop_no,
        potential_land_development_type,
        phu_yield,
        phu_yield AS developable_lots,
        land_area_ha,
        total_road_frontage,
        CASE
            WHEN phu_yield = 1 THEN 'Single Vacant Lot'
            WHEN phu_yield BETWEEN 2 AND 6 THEN 'Small Scale Development'
            WHEN phu_yield >= 7 THEN 'Large Scale Development'
        END AS development_category
    FROM property.property_grz_ldcap_vacant_viable
    
    UNION ALL
    
    SELECT 
        prop_no,
        potential_land_development_type,
        phu_yield,
        phu_yield AS developable_lots,
        land_area_ha,
        total_road_frontage,
        CASE
            WHEN phu_yield = 1 THEN 'Single Lot Infill'
            WHEN phu_yield BETWEEN 2 AND 6 THEN 'Small Scale Infill'
            WHEN phu_yield >= 7 THEN 'Large Scale Infill'
        END AS development_category 
    FROM property.property_grz_ldcap_infill_viable
)

, summary AS (
SELECT
    potential_land_development_type,
    development_category,
    COUNT(*) AS developable_properties,
    SUM(developable_lots) AS total_developable_lots,
    SUM(phu_yield) AS total_phu_yield,
    SUM(land_area_ha) AS total_land_area_ha
FROM developable
GROUP BY 
    potential_land_development_type,
    development_category
ORDER BY 
    potential_land_development_type,
    development_category
)

SELECT row_number() OVER ()::integer AS fid,
*,
ST_GeomFromText('MULTIPOLYGON EMPTY', 2193)::geometry(MultiPolygon, 2193) AS geom
FROM summary




	

WITH DATA;

ALTER TABLE property.property_grz_ldcap_summary
    OWNER TO postgres;

GRANT ALL ON TABLE property.property_grz_ldcap_summary TO postgres;
GRANT ALL ON TABLE property.property_grz_ldcap_summary TO wdc;
GRANT SELECT ON TABLE property.property_grz_ldcap_summary TO wdc_gisprod;


DO
$do$
BEGIN
EXECUTE format($$COMMENT ON MATERIALIZED VIEW property.property_grz_ldcap_summary is 'Regenerated by Stored Procedure %s'$$, LOCALTIMESTAMP);
END
$do$
$BODY$;

ALTER PROCEDURE property.create_mv_property_grz_ldcap_summary()
    OWNER TO postgres;

GRANT EXECUTE ON PROCEDURE property.create_mv_property_grz_ldcap_summary() TO PUBLIC;

GRANT EXECUTE ON PROCEDURE property.create_mv_property_grz_ldcap_summary() TO postgres;

GRANT EXECUTE ON PROCEDURE property.create_mv_property_grz_ldcap_summary() TO wdc;

GRANT EXECUTE ON PROCEDURE property.create_mv_property_grz_ldcap_summary() TO wdc_gisprod;

