-- PROCEDURE: property.create_mv_property_grz_ldcap_building_quadrant_summary()

-- DROP PROCEDURE IF EXISTS property.create_mv_property_grz_ldcap_building_quadrant_summary();

CREATE OR REPLACE PROCEDURE property.create_mv_property_grz_ldcap_building_quadrant_summary(
	)
LANGUAGE 'sql'
AS $BODY$
DROP MATERIALIZED VIEW IF EXISTS property.property_grz_ldcap_building_quadrant_summary;

CREATE MATERIALIZED VIEW property.property_grz_ldcap_building_quadrant_summary AS
WITH base AS (
    SELECT *
    FROM property.property_grz_ldcap_building_quadrant_stats
),

agg AS (
    SELECT
        prop_no,
        layer,

        COUNT(DISTINCT building_id) AS total_buildings,
        SUM(building_area) AS total_building_area,

        SUM(CASE WHEN quadrant_id = 1 THEN quadrant_building_count ELSE 0 END) AS ne_count,
        SUM(CASE WHEN quadrant_id = 2 THEN quadrant_building_count ELSE 0 END) AS nw_count,
        SUM(CASE WHEN quadrant_id = 3 THEN quadrant_building_count ELSE 0 END) AS se_count,
        SUM(CASE WHEN quadrant_id = 4 THEN quadrant_building_count ELSE 0 END) AS sw_count,

        SUM(CASE WHEN is_buildable_quadrant THEN 1 ELSE 0 END) AS buildable_quadrant_count,

        MAX(
            CASE 
                WHEN quadrant_is_front_facing THEN quadrant_id 
                ELSE NULL 
            END
        ) AS front_facing_quadrant_id,

        MAX(frontage_length) AS max_frontage_length,
        SUM(frontage_length) AS total_frontage_length

    FROM base
    GROUP BY prop_no, layer
),

final AS (
    SELECT
        a.prop_no,
        a.layer,
        a.total_buildings,
        a.total_building_area,
        a.ne_count,
        a.nw_count,
        a.se_count,
        a.sw_count,
        a.buildable_quadrant_count,
        a.front_facing_quadrant_id,
        a.max_frontage_length,
        a.total_frontage_length,
        p.geom AS property_geom   -- ✅ added geometry at end
    FROM agg a
    JOIN property.property_eplan_zones p
      ON a.prop_no = p.prop_no
)

SELECT
    ROW_NUMBER() OVER (ORDER BY prop_no) AS fid,
    *
FROM final;

-- Primary key
CREATE UNIQUE INDEX property_grz_ldcap_bqs_summary_pk
ON property.property_grz_ldcap_building_quadrant_summary (fid);

-- Lookups
CREATE INDEX property_grz_ldcap_bqs_summary_prop_idx
ON property.property_grz_ldcap_building_quadrant_summary (prop_no);

CREATE INDEX property_grz_ldcap_bqs_summary_layer_idx
ON property.property_grz_ldcap_building_quadrant_summary (layer);

-- ✅ Spatial index for property geometry
CREATE INDEX property_grz_ldcap_bqs_summary_geom_idx
ON property.property_grz_ldcap_building_quadrant_summary
USING GIST (property_geom);

DO
$do$
BEGIN
EXECUTE format($$COMMENT ON MATERIALIZED VIEW property.property_grz_ldcap_building_quadrant_summary is 'Regenerated by Stored Procedure %s'$$, LOCALTIMESTAMP);
END
$do$
$BODY$;

ALTER PROCEDURE property.create_mv_property_grz_ldcap_building_quadrant_summary()
    OWNER TO postgres;

GRANT EXECUTE ON PROCEDURE property.create_mv_property_grz_ldcap_building_quadrant_summary() TO PUBLIC;

GRANT EXECUTE ON PROCEDURE property.create_mv_property_grz_ldcap_building_quadrant_summary() TO postgres;

GRANT EXECUTE ON PROCEDURE property.create_mv_property_grz_ldcap_building_quadrant_summary() TO wdc;

GRANT EXECUTE ON PROCEDURE property.create_mv_property_grz_ldcap_building_quadrant_summary() TO wdc_gisprod;

