-- PROCEDURE: property.create_mv_property_grz_ldcap_fully_developed()

-- DROP PROCEDURE IF EXISTS property.create_mv_property_grz_ldcap_fully_developed();

CREATE OR REPLACE PROCEDURE property.create_mv_property_grz_ldcap_fully_developed(
	)
LANGUAGE 'sql'
AS $BODY$
DROP MATERIALIZED VIEW IF EXISTS property.property_grz_ldcap_fully_developed;

CREATE MATERIALIZED VIEW property.property_grz_ldcap_fully_developed
TABLESPACE pg_default
AS

WITH excl AS (
    -- 1a. Facilities: Health facilities, Rest Homes, Pensioner Housing, Schools, Campgrounds, Prisons, Justice Facilities, Marae, Religious Activities, Fuel Facilities 
    SELECT p.prop_no
    FROM property.property p
    CROSS JOIN (
        SELECT ST_Union(geom) AS geom 
        FROM general.whanganui_local_facilities
    ) wlf
    WHERE ST_Intersects(ST_PointOnSurface(p.geom), wlf.geom)

    UNION ALL

    -- 1b. Open Space Zone
    SELECT p.prop_no
    FROM property.property p
    CROSS JOIN (
        SELECT ST_Union(geom) AS geom 
        FROM eplan.osz_open_space_zone
    ) osz
    WHERE ST_Intersects(ST_PointOnSurface(p.geom), osz.geom)

    UNION ALL

    -- 2. Non-dominant GRZ
    SELECT prop_no
    FROM property.property_eplan_zones_multiples
    WHERE layer = 'grz_general_residential_zone'
      AND overlap < 40

	UNION ALL

	-- infill property
	SELECT prop_no
	FROM property.property_grz_ldcap_infill_viable

	UNION ALL

	-- vacant property
	SELECT prop_no
	FROM property.property_grz_ldcap_vacant_viable

)

,potential AS (
	SELECT 
		p.prop_no,
		'Fully Developed' AS potential_land_development_type,
		1 AS total_potential_lots,
		ROUND(ST_Area(p.geom)::numeric,3) As total_area_calc,
		p.geom
	FROM property.property_eplan_zones p
	WHERE p.layer = 'grz_general_residential_zone'
	AND NOT EXISTS (
	    SELECT 1 FROM excl e WHERE e.prop_no = p.prop_no
		)

)

SELECT row_number() OVER (ORDER BY p.prop_no) AS fid,
p.prop_no,
p.potential_land_development_type,
0 AS phu_yield,
p.total_area_calc / 10000 AS land_area_ha,
p.total_area_calc,
(SELECT total_road_frontage FROM property.property_grz_ldcap_viability_overlay_analysis qs WHERE p.prop_no = qs.prop_no) AS total_road_frontage,
p.geom
FROM potential p

WITH DATA;

ALTER TABLE property.property_grz_ldcap_fully_developed
    OWNER TO postgres;

GRANT ALL ON TABLE property.property_grz_ldcap_fully_developed TO postgres;
GRANT ALL ON TABLE property.property_grz_ldcap_fully_developed TO wdc;
GRANT SELECT ON TABLE property.property_grz_ldcap_fully_developed TO wdc_gisprod;

CREATE INDEX property_grz_ldcap_fully_developed_fid_idx
    ON property.property_grz_ldcap_fully_developed USING btree
    (fid)
    TABLESPACE pg_default;
CREATE INDEX property_grz_ldcap_fully_developed_prop_no_idx
    ON property.property_grz_ldcap_fully_developed USING btree
    (prop_no)
    TABLESPACE pg_default;
CREATE INDEX property_grz_ldcap_fully_developed_geom_idx
    ON property.property_grz_ldcap_fully_developed USING gist
    (geom)
    TABLESPACE pg_default;
DO
$do$
BEGIN
EXECUTE format($$COMMENT ON MATERIALIZED VIEW property.property_grz_ldcap_fully_developed is 'Regenerated by Stored Procedure %s'$$, LOCALTIMESTAMP);
END
$do$
$BODY$;

ALTER PROCEDURE property.create_mv_property_grz_ldcap_fully_developed()
    OWNER TO postgres;

GRANT EXECUTE ON PROCEDURE property.create_mv_property_grz_ldcap_fully_developed() TO PUBLIC;

GRANT EXECUTE ON PROCEDURE property.create_mv_property_grz_ldcap_fully_developed() TO postgres;

GRANT EXECUTE ON PROCEDURE property.create_mv_property_grz_ldcap_fully_developed() TO wdc;

GRANT EXECUTE ON PROCEDURE property.create_mv_property_grz_ldcap_fully_developed() TO wdc_gisprod;

