-- Create table
CREATE TABLE property.property_grz_ldcap_exclusion_thresholds (
    fid INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    metric_name TEXT NOT NULL,

    operator TEXT NOT NULL CHECK (
        operator IN ('>', '>=', '<', '<=', '=', 'BETWEEN')
    ),

    -- Single-value threshold
    threshold NUMERIC,

    -- Range thresholds (used only for BETWEEN)
    threshold_min NUMERIC,
    threshold_max NUMERIC,

    -- Geometry column (NZTM)
    geom geometry(MultiPolygon, 2193) NOT NULL
        DEFAULT ST_GeomFromText('MULTIPOLYGON EMPTY', 2193),

    -- Data integrity rule:
    CHECK (
        -- For non-BETWEEN operators
        (operator <> 'BETWEEN'
            AND threshold IS NOT NULL
            AND threshold_min IS NULL
            AND threshold_max IS NULL
        )
        OR
        -- For BETWEEN operator
        (operator = 'BETWEEN'
            AND threshold IS NULL
            AND threshold_min IS NOT NULL
            AND threshold_max IS NOT NULL
        )
    )
);

-- Optional: ensure metric names are unique
CREATE UNIQUE INDEX ux_property_grz_ldcap_exclusion_thresholds_metric
ON property.property_grz_ldcap_exclusion_thresholds (metric_name);




ALTER TABLE property.property_grz_ldcap_exclusion_thresholds
    OWNER TO postgres;

GRANT ALL ON TABLE property.property_grz_ldcap_exclusion_thresholds TO postgres;
GRANT ALL ON TABLE property.property_grz_ldcap_exclusion_thresholds TO wdc;
GRANT SELECT ON TABLE property.property_grz_ldcap_exclusion_thresholds TO wdc_gisprod;

-- Insert current threshold rules

INSERT INTO property.property_grz_ldcap_exclusion_thresholds (metric_name, operator, threshold)
VALUES
    ('lidar2020_dem_1m_slope_geq20', '>', 30),
    ('land_stability_assessment_area_a', '>', 0),
    ('land_stability_assessment_area_b', '>=', 30),
    ('flood_risk_area_a', '>=', 30),
    ('flood_risk_area_b', '>=', 30),
    ('ht_powerlines_10m_setback', '>=', 30),
    ('ht_pylons_12m_setback', '>=', 30),
    ('lidar2020_dem_depression_areas_gt_300', '>=', 30),
    ('highliquefaction', '>=', 30);




ALTER TABLE property.property_grz_ldcap_exclusion_thresholds
ADD COLUMN source_column TEXT;

UPDATE property.property_grz_ldcap_exclusion_thresholds
SET source_column = CASE metric_name
    WHEN 'lidar2020_dem_1m_slope_geq20' THEN 'prop_overlap_pct_lidar2020_dem_1m_slope_geq20'
    WHEN 'land_stability_assessment_area_a' THEN 'prop_overlap_pct_land_stability_assessment_area_a'
    WHEN 'land_stability_assessment_area_b' THEN 'prop_overlap_pct_land_stability_assessment_area_b'
    WHEN 'flood_risk_area_a' THEN 'prop_overlap_pct_flood_risk_area_a'
    WHEN 'flood_risk_area_b' THEN 'prop_overlap_pct_flood_risk_area_b'
    WHEN 'ht_powerlines_10m_setback' THEN 'prop_overlap_pct_ht_powerlines_10m_setback'
    WHEN 'ht_pylons_12m_setback' THEN 'prop_overlap_pct_ht_pylons_12m_setback'
    WHEN 'lidar2020_dem_depression_areas_gt_300' THEN 'prop_overlap_pct_lidar2020_dem_depression_areas_gt_300'
    WHEN 'highliquefaction' THEN 'prop_overlap_pct_highliquefaction'
END;

